# Generated by Django 4.0.2 on 2023-04-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_id_alter_product_id'),
        ('shop', '0002_alter_category_id_alter_product_id 2'),
    ]

    operations = [
    ]
