# Generated by Django 4.0.2 on 2023-04-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_braintree_id 2'),
        ('orders', '0003_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
    ]
